# Generated by Django 2.0.4 on 2018-05-15 08:53

from django.db import migrations, models
import website.models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='post',
            name='notefile',
            field=models.FileField(blank=True, null=True, upload_to=website.models.Post.makepath),
        ),
    ]
