# Generated by Django 2.0.4 on 2018-05-17 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20180515_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='subneddit',
            name='sidebar',
            field=models.TextField(blank=True, verbose_name='Sidebar Text'),
        ),
    ]
